### ISSUE TITLE
кнопка назад

### ISSUE THREAD

**Issue by Vitaly-nvkz** [portalsftdev/dm#2]
в карточке товара когда меняешь цвет нажимаешь назад должен произойти переход в каталог

**Comment by portalsftdev** [comment]
Отслеживание предыдущей страницы (список товаров категории или список товаров бренда) по HTTP-заголовку Referrer и последующее перенаправление пользователя на эту страницу при нажатии на кнопку "Назад" не дает ожидаемого результата. Переход происходит корректно, но в таком случае становится недоступна кнопка "Вперед" и при нажатии кнопки "Назад" происходит переход на карточку товара, так как именно эта страница является предыдущей. Как это работает можно посмотреть на development-версии сайта.

Для решения проблемы есть два более простых пути:
1. В карточке товара сделать кнопку родительской категории
2. Сделать AJAX-загрузку контента при выборе другого цвета (и других опций товара) без манипуляции историей браузера (без изменения URL), в этом случае будет работать как ожидается. Правда, при этом подходе в других случаях может возникать не совсем очевидное поведение, например: пользователь заходит в карточку товара, у товара цвет "Золото", он меняет цвет, например на "Платина", затем обновляет страницу и опять попадает на товар с цветом "Золото"

**Comment by spirally** [comment]
Хлебные крошки решат проблему. Вообще они были в первоначальном шаблоне, но Андрей настоял, что они не нужны))
Я их верну, и это решит не только проблему возврата на уровень выше, но и еще две:
 - возврат на другие уровни, вплоть до корня каталога
 - сразу будет видно, в каком мы разделе сайта

**Comment by portalsftdev** [comment]
Добавлена AJAX-загрузка без манипуляции историей браузера: f86e5746804d8d1f64b1014de56e7dfba876fbfa.

**Comment by portalsftdev** [comment]
Все работает как ожидается.
