### ISSUE TITLE
Фильтр "Акция месяца"

### ISSUE THREAD

**Issue by Vitaly-nvkz** [portalsftdev/dm#3]
Добавить фильтр Акция месяца в категории товаров

**Comment by portalsftdev** [comment]
Добавлено: ba3f270a03d14e5ad3f98d7e4c7fbfa0102a74c9. Если работает как ожидается, то прошу подтвердить и закрыть вопрос

**Comment by portalsftdev** [comment]
Все работает как ожидается.
